//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoriesProduct
    {
        public string IdAccessories { get; set; }
        public string IdProduct { get; set; }
        public string Placement { get; set; }
        public string Width { get; set; }
        public string Lengh { get; set; }
        public Nullable<int> Turn { get; set; }
        public int Count { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Product Product { get; set; }
    }
}
