//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cloth()
        {
            this.FabricWarehouse = new HashSet<FabricWarehouse>();
        }
    
        public string ArticleNumber { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Picture { get; set; }
        public string Image { get; set; }
        public string Composition { get; set; }
        public int Width { get; set; }
        public int Length { get; set; }
        public int Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FabricWarehouse> FabricWarehouse { get; set; }
        public virtual Product Product { get; set; }
    }
}
