//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrance
    {
        public int IdRecord { get; set; }
        public Nullable<System.DateTime> DateEntrance { get; set; }
        public string NumberEntrance { get; set; }
        public Nullable<int> IdPrivder { get; set; }
        public string ArticleCloth { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Sum { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
