//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricWarehouse
    {
        public string Roll { get; set; }
        public string ArticleCloth { get; set; }
        public int Width { get; set; }
        public int Length { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
