//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SewingFactoryEntities : DbContext
    {
        public SewingFactoryEntities()
            : base("name=SewingFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessories> Accessories { get; set; }
        public virtual DbSet<AccessoriesProduct> AccessoriesProduct { get; set; }
        public virtual DbSet<Cloth> Cloth { get; set; }
        public virtual DbSet<CustomProducts> CustomProducts { get; set; }
        public virtual DbSet<FabricWarehouse> FabricWarehouse { get; set; }
        public virtual DbSet<HardwareWarehouse> HardwareWarehouse { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
