//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareWarehouse
    {
        public string IdAccessories { get; set; }
        public int Party { get; set; }
        public int Count { get; set; }
    
        public virtual Accessories Accessories { get; set; }
    }
}
